### ISSUE TITLE
Use optimized random number generator from https://xkcd.com/221/

### ISSUE THREAD

**Issue by oscardssmith** [giordano/RandomBasedArrays.jl#4]
By using this random number generator, we could significantly improve the performance of this library.

**Comment by oscardssmith** [comment]
I promise the issue number wasn't purposeful.

**Comment by giordano** [comment]
I think the RNG should be defined in `StableRNGs`: https://github.com/JuliaRandom/StableRNGs.jl/issues/6

**Comment by oscardssmith** [comment]
Closed by https://github.com/wildart/Xkcd221
